"""
Disaster-risk prediction (Objective 3).

Trains and compares three approaches on the historical dataset:
  * Threshold baseline  - what a manual / rule-of-thumb early-warning does (river above danger mark
                          or very heavy rain => alert). Used as the comparison point in the evaluation.
  * Logistic Regression - linear probabilistic model.
  * Random Forest       - non-linear ensemble (the model that is served if it wins on macro-F1).

The winning model predicts severity classes 0-3 with probabilities, from which we derive:
  likelihood  = P(severity >= Moderate)
  risk_score  = expected severity / 3   (0..1)
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_fscore_support
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from data_gen import FEATURES, SEVERITY_LABELS, TARGET, load_historical

MODEL_DIR = Path(__file__).parent / "models"
MODEL_PATH = MODEL_DIR / "risk_model.joblib"
METRICS_PATH = MODEL_DIR / "risk_metrics.json"


def threshold_baseline(df: pd.DataFrame) -> np.ndarray:
    """Traditional threshold-based warning: escalate by fixed cut-offs on river level and rain."""
    sev = np.zeros(len(df), dtype=int)
    sev[(df["river_ratio"] >= 0.75) | (df["rain_24h_mm"] >= 65)] = 1
    sev[(df["river_ratio"] >= 0.95) | (df["rain_24h_mm"] >= 115)] = 2
    sev[(df["river_ratio"] >= 1.15) | (df["rain_24h_mm"] >= 180)] = 3
    return sev


def _score(y_true, y_pred) -> dict:
    p, r, f, _ = precision_recall_fscore_support(y_true, y_pred, average="macro", zero_division=0)
    # Operationally the key question is "did we catch High/Severe events?"
    yt = (np.asarray(y_true) >= 2).astype(int)
    yp = (np.asarray(y_pred) >= 2).astype(int)
    bp, br, bf, _ = precision_recall_fscore_support(yt, yp, average="binary", zero_division=0)
    return {
        "accuracy": round(float(accuracy_score(y_true, y_pred)), 4),
        "precision_macro": round(float(p), 4),
        "recall_macro": round(float(r), 4),
        "f1_macro": round(float(f), 4),
        "high_severe_precision": round(float(bp), 4),
        "high_severe_recall": round(float(br), 4),
        "high_severe_f1": round(float(bf), 4),
    }


def train(force: bool = True) -> dict:
    MODEL_DIR.mkdir(exist_ok=True)
    df = load_historical()
    X, y = df[FEATURES], df[TARGET]
    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=7, stratify=y)

    candidates = {
        "logistic_regression": make_pipeline(
            StandardScaler(), LogisticRegression(max_iter=2000, class_weight="balanced")
        ),
        "random_forest": RandomForestClassifier(
            n_estimators=250, max_depth=14, min_samples_leaf=2, class_weight="balanced", random_state=7, n_jobs=-1
        ),
    }

    results = {"threshold_baseline": _score(y_te, threshold_baseline(X_te))}
    fitted = {}
    for name, model in candidates.items():
        model.fit(X_tr, y_tr)
        results[name] = _score(y_te, model.predict(X_te))
        fitted[name] = model

    best_name = max(fitted, key=lambda n: results[n]["f1_macro"])
    best = fitted[best_name]
    cm = confusion_matrix(y_te, best.predict(X_te), labels=[0, 1, 2, 3]).tolist()

    importances = {}
    if best_name == "random_forest":
        importances = {f: round(float(v), 4) for f, v in zip(FEATURES, best.feature_importances_)}
        importances = dict(sorted(importances.items(), key=lambda kv: -kv[1]))

    metrics = {
        "data_source": os.getenv("HISTORICAL_DATA_SOURCE", "synthetic (generated by data_gen.py)"),
        "dataset_rows": int(len(df)),
        "train_rows": int(len(X_tr)),
        "test_rows": int(len(X_te)),
        "class_distribution": {SEVERITY_LABELS[int(k)]: int(v) for k, v in y.value_counts().sort_index().items()},
        "served_model": best_name,
        "models": results,
        "confusion_matrix": {"labels": SEVERITY_LABELS, "matrix": cm},
        "feature_importance": importances,
        "features": FEATURES,
    }
    joblib.dump({"model": best, "name": best_name}, MODEL_PATH)
    METRICS_PATH.write_text(json.dumps(metrics, indent=2))
    return metrics


_bundle = None


def _load():
    global _bundle
    if _bundle is None:
        if not MODEL_PATH.exists():
            train()
        _bundle = joblib.load(MODEL_PATH)
    return _bundle


def get_metrics() -> dict:
    if not METRICS_PATH.exists():
        train()
    return json.loads(METRICS_PATH.read_text())


def _clean_features(features: dict) -> dict:
    """Fill missing values with neutral defaults and clamp to plausible ranges."""
    defaults = {
        "rain_24h_mm": 0.0,
        "rain_72h_mm": None,
        "river_ratio": 0.4,
        "soil_saturation": 0.3,
        "humidity_pct": 60.0,
        "wind_kmh": 10.0,
        "elevation_m": 60.0,
    }
    bounds = {
        "rain_24h_mm": (0, 400),
        "rain_72h_mm": (0, 700),
        "river_ratio": (0, 2.0),
        "soil_saturation": (0, 1),
        "humidity_pct": (0, 100),
        "wind_kmh": (0, 200),
        "elevation_m": (0, 4000),
    }
    out = {}
    for k in FEATURES:
        v = features.get(k)
        if v is None:
            v = defaults[k]
        if v is None:  # rain_72h defaults to rain_24h
            v = out.get("rain_24h_mm", 0.0)
        lo, hi = bounds[k]
        out[k] = float(min(max(float(v), lo), hi))
    out["rain_72h_mm"] = max(out["rain_72h_mm"], out["rain_24h_mm"])
    return out


def predict(features: dict) -> dict:
    return predict_many([features])[0]


def predict_many(feature_list: list[dict]) -> list[dict]:
    bundle = _load()
    model = bundle["model"]
    cleaned = [_clean_features(f) for f in feature_list]
    X = pd.DataFrame(cleaned)[FEATURES]
    proba = model.predict_proba(X)
    # Ensure 4 columns even if a class was absent in training.
    full = np.zeros((len(X), 4))
    for i, cls in enumerate(model.classes_):
        full[:, int(cls)] = proba[:, i]

    out = []
    for row, feats in zip(full, cleaned):
        sev = int(np.argmax(row))
        out.append(
            {
                "severity": sev,
                "severity_label": SEVERITY_LABELS[sev],
                "probabilities": {SEVERITY_LABELS[i]: round(float(p), 4) for i, p in enumerate(row)},
                "likelihood": round(float(1.0 - row[0]), 4),
                "risk_score": round(float(np.dot(row, np.arange(4)) / 3.0), 4),
                "model": bundle["name"],
                "features_used": feats,
            }
        )
    return out


if __name__ == "__main__":
    m = train()
    print(json.dumps(m["models"], indent=2))
    print("served:", m["served_model"])
